### PR TITLE
Add jekyll 3.1.0 support. 

### PR DESCRIPTION
**Pull request by equinusocio**
Please update readme yourself.

### CODE REVIEW

**Comment by kurtsson** [comment]
This is great work! However it will break compability with old Jekyll right?

**Comment by equinusocio** [comment]
Yes. Maybe just make a legacy branch with the old one

**Comment by Anthony-Gaudino** [comment]
I'm working on branch [1.4.0](/Anthony-Gaudino/jekyll-multiple-languages-plugin/tree/1.4.0) which will include support for Jekyll 3.1.0, it should be backwards compatible with 2.5.3.

I already had the code all done and working (same code as your pull request), but I decided to break those changes into small commits that are easily traceable in history, I will also make some changes and more tests to make sure it works fine.

**Comment by Anthony-Gaudino** [comment]
Version 1.4.0 is now compatible with Jekyll 3 and is backwards compatible with version 2.

**Pull request closed without merging**
