### PR TITLE
If include not found, falls back to default lang

### LINKED ISSUE #123: Fallback on translate_file does not work
Fallbacks for translate_file don't work correctly:

```
Liquid Exception: Included file 'xxx/features.html' not found in /Users/xxx/xxx/_i18n/es directory in index.html
```

### PR DESCRIPTION
**Pull request by joshcummingsdesign**
Looking to resolve #123 by falling back to the default language if an include is not found in another language.

### CODE REVIEW

**Comment by kurtsson** [comment]
Hi @joshcummingsdesign. The main administrator @Anthony-Gaudino, has disappeared so we are in a bit of a sad state here. I still have access to the Ruby Gem and can release new versions but I do not use any Jekyll sites and have no way of verifying PRs. In short this project really need a new owner, is that you? Or can you atleast verify all PRs so I can merge and make a release?

**Comment by joshcummingsdesign** [comment]
@kurtsson I can definitely help verify PRs. What's needed on my end?

**Comment by kurtsson** [comment]
> @kurtsson I can definitely help verify PRs. What's needed on my end?

Just verify that they work and can be merged. If you write in the comments for a PR that it's ready for merge, I can merge and release.

**Comment by joshcummingsdesign** [comment]
Duplicate of #130 - closing

**Pull request closed without merging**
